version: '3'
services:
  adminer:
    container_name: Adminer
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    environment:
      ADMINER_DESIGN: pepa-linha

  mysql:
    container_name: Mysql
    image: mysql:latest
    env_file:
      - ./docker.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
